version: "3.8"

services:
  app:
    container_name: abn-amro-assignment
    image: abn-amro-assignment
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000